apiVersion: v1
kind: Pod
metadata:
  name: mysql-volume
spec:
  containers:
  - name: mysql
    image: mysql
    volumeMounts:
    - name: mysql-data
      mountPath: /var/lib/mysql
    env:
    - name: MYSQL_USER
      value: easytraining
    - name: MYSQL_DATABASE
      value: easy
    - name: MYSQL_PASSWORD
      value: easy
    - name: MYSQL_ROOT_PASSWORD
      value: password

  volumes:
  - name: mysql-data
    hostPath:
      path: /data-volume
      type: Directory
