apiVersion: v1
kind: PersistentVolume
metadata:
  name: vafe-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data-pv"
    type: DirectoryOrCreate

